### ISSUE TITLE
 Startup crash using Docker

### ISSUE THREAD

**Issue by redghc** [Luligu/matterbridge#79]
Hi, I'm having issues deploying versions from 1.3.5 to 1.3.10. (I haven't tested earlier versions).

Here are my logs:
```
CLI: Matterbridge.loadInstance() failed with error: SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)

CLI: Matterbridge.loadInstance() failed with error: SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)

CLI: Matterbridge.loadInstance() failed with error: SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)

CLI: Matterbridge.loadInstance() failed with error: SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)

CLI: Matterbridge.loadInstance() failed with error: SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)

CLI: Matterbridge.loadInstance() failed with error: SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)

CLI: Matterbridge.loadInstance() failed with error: SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)

CLI: Matterbridge.loadInstance() failed with error: SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)

CLI: Matterbridge.loadInstance() failed with error: SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
```

I also attach my docker-compose.yaml file:

```
version: "3"

services:
  matter-bridge:
    image: luligu/matterbridge:${VERSION-latest}
    container_name: matter-bridge

    restart: always

    volumes:
      - ${PLUGIN_PATH}:/Matterbridge
      - ${STORAGE_PATH}:/.matterbridge

    environment:
      PUID: ${PUID-1000}
      PGID: ${PGID-1000}

    user: ${PUID-1000}:${PGID-1000}

    network_mode: host
```

Upon reviewing the generated folders, I found only the following file with this content:
File: `0d0a2ac6163e36f3f2349c77671004edfe3d5e1abbef93cbb583acec8d01481b`

Content:
```
{"key":"storageNames","value":["matterbridge"]}

```

**Comment by redghc** [comment]
Finally, it was my fault. I'm leaving the corrected .yaml file and closing the issue.
Regards

```
version: "3"

services:
  matter-bridge:
    image: luligu/matterbridge:${VERSION-latest}
    container_name: matter-bridge

    restart: always

    volumes:
      - ${PLUGIN_PATH}:/root/Matterbridge
      - ${STORAGE_PATH}:/root/.matterbridge

    network_mode: host

```
